//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerAdminPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int Id { get; set; }
        public Nullable<long> CreatedTime { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Message { get; set; }
    }
}
