//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerAdminPanel
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Core.Objects;
	using System.Data.Entity.Infrastructure;
	using System.Linq;

	public partial class MessengerContext : DbContext
    {
        public MessengerContext()
            : base("name=MessengerConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<Conversation> Conversation { get; set; }
        public virtual DbSet<EventLog> EventLog { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfo { get; set; }
        public virtual DbSet<User> User { get; set; }

		public void Refresh()
		{
			var objectContext = ((IObjectContextAdapter)this).ObjectContext;
			var objects = (from entry in objectContext.ObjectStateManager.GetObjectStateEntries(
													   EntityState.Added
													  | EntityState.Deleted
													  | EntityState.Modified
													  | EntityState.Unchanged)
						   where entry.EntityKey != null
						   select entry.Entity);

			objectContext.Refresh(RefreshMode.StoreWins, objects);
		}
	}
}
