//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerAdminPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int Id { get; set; }
        public Nullable<long> BirthDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Picture { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
